# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_install', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_serial', models.CharField(max_length=20)),
                ('task_host', models.CharField(max_length=30)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result', models.BooleanField()),
            ],
        ),
#        migrations.AddField(
#            model_name='appgroup',
#            name='deploytype',
#            field=models.CharField(default='jenkins', max_length=10),
#        ),
        migrations.AddField(
            model_name='tasklog',
            name='appgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_install.appgroup'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='excute_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
